Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -36,36 +36,12 @@ jobs:
             npm install
             npm update
             npm run build 
-            
+          
 
         
       - save_cache:
           paths: [frontend/node_modules]
           key: frontend-build
-
-
-  build-backend:
-    docker:
-      - image: cimg/node:13.8.0
-    
-    # Add steps to the job
-    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [backend-build]
-      - run:
-          name: Build back-end 
-          command: |
-            cd backend
-            npm install
-            npm run build
-
-            
-      - save_cache:
-          paths: [backend/node_modules]
-          key: backend-build
-
 
 
   test-frontend:
@@ -92,6 +68,47 @@ jobs:
             npm install
             npm update
             npm run test   
+
+
+  scan-frontend:
+      docker:
+        - image: circleci/node:13.8.0
+      steps:
+        - checkout
+        - restore_cache:
+            keys: [frontend-build]
+        - run:
+            name: Scan frontend dependencies
+            command: |
+              cd frontend
+              npm install
+              npm update
+              npm audit fix --audit-level=critical --force
+              npm audit --audit-level=critical
+              
+             # https://www.codegrepper.com/code-examples/javascript/npm+ERR%21+code+ELIFECYCLE+npm+ERR%21+errno+1
+
+
+  build-backend:
+    docker:
+      - image: cimg/node:13.8.0
+    
+    # Add steps to the job
+    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
+    steps:
+      - checkout
+      - restore_cache:
+          keys: [backend-build]
+      - run:
+          name: Build back-end 
+          command: |
+            cd backend
+            npm install
+            npm run build     
+      - save_cache:
+          paths: [backend/node_modules]
+          key: backend-build
+
 
   test-backend:
     docker:
@@ -145,28 +162,11 @@ jobs:
           name: backend test
           command: |
             cd backend
-            npm install 
-            npm update
+            npm install npm
+            npm install --save-dev webpack@5.72.0
             npm audit fix --audit-level=critical --force
             npm audit --audit-level=critical
 
-  scan-frontend:
-      docker:
-        - image: circleci/node:13.8.0
-      steps:
-        - checkout
-        - restore_cache:
-            keys: [frontend-build]
-        - run:
-            name: Scan frontend dependencies
-            command: |
-              cd frontend
-              npm install
-              npm update
-              npm audit fix --audit-level=critical --force
-              npm audit --audit-level=critical
-              
-             # https://www.codegrepper.com/code-examples/javascript/npm+ERR%21+code+ELIFECYCLE+npm+ERR%21+errno+1
 
   scan-backend:
     docker:
@@ -178,97 +178,21 @@ jobs:
       - run:
           name: Scan backend dependencies
           command: |
-             cd backend
-             npm install 
-             npm update
+             cd backend        
+             npm install
              npm install --save-dev webpack@5.72.0
              npm audit fix --audit-level=critical --force
              npm audit --audit-level=critical
 
 
-        
-  configure-infrastructure:
-      docker:
-        # Docker image here that supports Ansible
-        - image: python:3.7-alpine3.11
-        
-      steps: 
-        # Checkout code from git
-        # Add ssh keys with fingerprint
-        # attach workspace
-        # Install dependencies
-        # Configure server
-        - checkout
-        - add_ssh_keys:
-            fingerprints: ["19:a9:98:05:4a:cd:5c:1d:88:17:a8:30:dc:05:c5:4d"] 
-
-        - attach_workspace:
-            at: ~/
-            
-        - run:
-            name: Install dependencies
-            command: |
-              # Your code here
-              apk add --update ansible
-              yum -y install tar gzip
-              apk add --update tar 
-              apk add --update gzip
-              pip install awscli
-
-              # exit 1
-        - run:
-            name: Configure server
-            command: |
-              # Your code here
-              pwd
-              cat .circleci/ansible/inventory.txt
-
-              echo ENVIRONMENT=production > "backend/.env"
-              ls
-              echo TYPEORM_CONNECTION=postgres >> "backend/.env"
-              echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> "backend/.env"
-              echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> "backend/.env"
-              echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> "backend/.env"
-              echo NODE_ENV=production >> "backend/.env"
-
-              echo TYPEORM_HOST=$TYPEORM_HOST >> "backend/.env"
-              echo TYPEORM_PORT=$TYPEORM_PORT >> "backend/.env"
-              echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
-              echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
-              echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"
-              ansible-playbook -i .circleci/ansible/inventory.txt .circleci/ansible/configure-server.yml
-              cat backend/.env
-              ls backend
-
-              # exit 1
-
-
-        # Here's where you will add some code to rollback on failure  
-        - run:
-            name: Install AWS CLI for rollback
-            when: on_fail
-            command: |
-              apk add --update py3-pip && pip3 install --upgrade pip && pip3 install awscli
-        - persist_to_workspace:
-            root: ~/
-            paths:
-              - project/backend
-        - destroy-environment:
-            workflow_id: "${CIRCLE_WORKFLOW_ID}"      
-
-        - restore_cache:
-            keys: [backend-build]
-        - run: 
-            name: Install dependencies
-            command: |
-              apk add --update ansible # install the dependencies needed
 
   deploy-infrastructure:
     docker:
       # Docker image here that supports AWS CLI
       # - image: circleci/node:13.8.0
-       - image: amazon/aws-cli
-     
+      - image: amazon/aws-cli
+        user: root
+
     steps:
       # Checkout code from git
       - checkout
@@ -277,6 +201,9 @@ jobs:
           command: |
               yum -y install tar 
               yum -y install gzip
+
+      - attach_workspace:
+          at: ~/          
       
       # Gzip is the standard file compression for Unix and Linux systems. 
       # Gzip is faster than ZIP while compressing and decompressing. ZIP is 
@@ -325,14 +252,216 @@ jobs:
                 --output text >> inventory            
             # exit 1
 
-      # DevOps Monitoring tutorial | How To Install Prometheus | AWS Amazon Linux      
-      # https://www.youtube.com/watch?v=hfWl8k8m4n8
-      #- run:
-      #    name: update yum package repositories
-      #    command: |
-            # Your code here
-       #       sudo yum update -y \
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/.circleci/ansible/inventory.txt
 
+
+      # Here's where you will add some code to rollback on failure      
+      - destroy-environment:
+          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
+
+      # # DevOps Monitoring tutorial | How To Install Prometheus | AWS Amazon Linux      
+      # # https://www.youtube.com/watch?v=hfWl8k8m4n8
+      # - run:
+      #     name: update yum package repositories
+      #     command: |
+      #       # Your code here
+      #         sudo yum update -y \
+
+          
+  configure-infrastructure:
+    docker:
+      # Docker image here that supports Ansible
+    - image: python:3.7-alpine3.11
+      
+    steps: 
+    # Checkout code from git
+    # Add ssh keys with fingerprint
+    # attach workspace
+    # Install dependencies
+    # Configure server
+    - checkout
+    - add_ssh_keys:
+        fingerprints: ["19:a9:98:05:4a:cd:5c:1d:88:17:a8:30:dc:05:c5:4d"] 
+
+    - attach_workspace:
+        at: ~/
+        
+    - run:
+        name: Install dependencies
+        command: |
+          # Your code here
+          apk add --update ansible
+          yum -y install tar gzip
+          apk add --update tar 
+          apk add --update gzip
+          pip install awscli
+
+          # exit 1
+    - run:
+        name: Configure server
+        command: |
+          # Your code here
+          pwd
+          cat .circleci/ansible/inventory.txt
+
+          echo ENVIRONMENT=production > "backend/.env"
+          ls
+          echo TYPEORM_CONNECTION=postgres >> "backend/.env"
+          echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> "backend/.env"
+          echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> "backend/.env"
+          echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> "backend/.env"
+          echo NODE_ENV=production >> "backend/.env"
+
+          echo TYPEORM_HOST=$TYPEORM_HOST >> "backend/.env"
+          echo TYPEORM_PORT=$TYPEORM_PORT >> "backend/.env"
+          echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
+          echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
+          echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"
+          ansible-playbook -i .circleci/ansible/inventory.txt .circleci/ansible/configure-server.yml
+          no_output_timeout: 30m
+          cat backend/.env
+          ls backend
+
+          # exit 1
+
+    - destroy-environment:
+        workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
+
+  run-migrations:
+    docker:
+    # Docker image here that supports NodeJS
+    - image: circleci/node:13.8.0
+
+    steps:
+    # Checkout code from git
+    - checkout
+    - restore_cache:
+        keys: [backend-build]
+
+    - run:
+        name: Install awscli
+        command: |
+          sudo apt-get update
+          sudo apt-get install -y awscli curl 
+
+    - run:
+        name: Run migrations
+        command: |
+          # Your code here
+          cd backend
+          npm install
+          npm run build
+          npm run migrations > migrations_dump.txt
+          cat migrations_dump.txt
+          # exit 1
+    - run:
+        name: Send migration status to kvdb.io
+        command: |
+          # Your code here
+          if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+          then
+            curl https://kvdb.io/CNXVssXp4xn36vXQNvVzgY/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+          fi
+          # exit 1
+          
+    - destroy-environment:
+        workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
+          
+    # Here's where you will add some code to rollback on failure      
+
+
+  deploy-frontend:
+    docker:
+    # Docker image here that supports AWS CLI
+    - image: amazon/aws-cli
+      user: root
+
+    steps:
+    # Checkout code from git
+    - checkout
+    - run:
+        name: Install tar/gzip utility
+        command: | 
+          yum -y install tar
+          yum -y install gzip
+    - attach_workspace:
+        at: ~/
+
+    - run:
+        name: Install dependencies
+        command: |
+          # your code here
+          curl -sL https://rpm.nodesource.com/setup_lts.x | bash -
+          yum -y install nodejs
+          yum install python3-pip -y
+
+    - run:
+        name: Get backend url
+        command: |
+          # your code here
+          export BACKEND_IP=$(aws ec2 describe-instances \
+          --query 'Reservations[*].Instances[*].PublicIpAddress' \
+          --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text)
+          export API_URL="http://${BACKEND_IP}:3030"
+          echo "${API_URL}"
+          echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+          cat frontend/.env
+
+
+    - run:
+        name: Deploy frontend objects
+        command: |
+          # your code here
+          cd frontend
+          npm install
+          #npm audit fix
+          #npm audit fix --force
+          npm run build
+          tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+          aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+
+    # Here's where you will add some code to rollback on failure      
+                  
+  deploy-backend:
+    docker:
+      # Docker image here that supports Ansible
+    - image: python:3.7-alpine3.11
+          
+    steps:
+      # Checkout code from git
+      # Add ssh keys with fingerprint
+      # attach workspace
+      - run:
+          name: Install dependencies
+          command: |
+            # your code here
+      - run:
+          name: Deploy backend
+          command: |
+            # your code here
+
+        # Here's where you will add some code to rollback on failure  
+      - run:
+          name: Install AWS CLI for rollback
+          when: on_fail
+          command: |
+              apk add --update py3-pip && pip3 install --upgrade pip && pip3 install awscli ansible
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/backend
+      - destroy-environment:
+          workflow_id: "${CIRCLE_WORKFLOW_ID}"      
+
+      - restore_cache:
+          keys: [backend-build]
+      - run: 
+          name: Install dependencies
+          command: |
+              apk add --update ansible # install the dependencies needed
 
 
       # Section 4: Surface Critical Server Errors for Diagnosis Using Centralized Logging
@@ -371,8 +500,124 @@ jobs:
       # https://askubuntu.com/questions/29359/how-to-add-a-user-without-home
       #
       # https://becloudready.com/automate-prometheus-deployment-with-ansible/
+      # https://superuser.com/questions/1543628/adduser-command-not-working-in-linux
       #
+      - run:
+          name: create prometheus user
+          command: |
+
+
+            # Your code here [sudo useradd --no-create-home prometheus]
+              sudo apt-get update
+              sudo apt-get install adduser
+              sudo adduser --no-create-home --shell /bin/false prometheus
+      - run:
+          name: create node_exporter user
+          command: |
+            # Your code here [sudo useradd --no-create-home node_exporter]
+              sudo adduser --no-create-home --shell /bin/false node_exporter
+              
+      - run:
+          name: create required prometheus directories        
+          command: |
+            # Your code here
+              sudo mkdir /etc/prometheus
+              sudo mkdir /etc/prometheus/consoles
+              sudo mkdir /etc/prometheus/console_libraries
+
+              sudo mkdir /var/lib/prometheus
+
+              sudo mkdir /usr/local/bin/prometheus
+              sudo mkdir /usr/local/bin/promtool
+
+
+      # chown [OPTIONS] USER[:GROUP] FILE(s) 
+      # https://linuxize.com/post/linux-chown-command/
+      - run:  
+          name: make prometheus user owner of required prometheus directories        
+          command: |       
+            # Your code here
+              sudo chown prometheus:prometheus /etc/prometheus 
+              sudo chown -R prometheus:prometheus /etc/prometheus/consoles
+              sudo chown -R prometheus:prometheus /etc/prometheus/console_libraries  
+
+              sudo chown prometheus:prometheus /usr/local/bin/prometheus
+              sudo chown prometheus:prometheus /usr/local/bin/promtool
       
+              sudo chown -R prometheus:prometheus /var/lib/prometheus
+              
+      # By default, Prometheus is not available in the Ubuntu 18.04 LTS (Bionic Beaver) 
+      # default repository. So you will need to add the repository for that.
+      #
+      # https://www.howtoforge.com/tutorial/monitor-ubuntu-server-with-prometheus/
+
+      - run:
+          name: Download latest stable release of prometheus and untar/install it
+          command: |
+            # Your code here use wget or curl to download prometheus. curl has flags. wget does not.
+            # wget https://github.com/prometheus/prometheus/releases/download/v2.21.0/prometheus-2.21.0.linux-amd64.tar.gz        
+              curl -LO https://github.com/prometheus/prometheus/releases/download/v2.21.0/prometheus-2.21.0.linux-amd64.tar.gz        
+              tar xvfz prometheus-2.21.0.linux-amd64.tar.gz
+              mv prometheus-2.21.0.linux-amd64 prometheus-files
+
+      # sudo apt-get update
+      # sudo apt-get install prometheus prometheus-node-exporter prometheus-pushgateway prometheus-alertmanager
+      # https://linuxhint.com/install-prometheus-ubuntu-18-04/
+      - run:
+          name: copy prometheus and promtool binary files from prometheus-files to /usr/local/bin/
+          command: |
+            # Your code here
+              sudo cp prometheus-files/prometheus /usr/local/bin/
+              sudo cp prometheus-files/promtool /usr/local/bin/
+
+      - run:
+          name: move the consoles and console_libraries directories from prometheus-files to /etc/prometheus
+          command: |
+            # Your code here
+              sudo cp -r prometheus-files/consoles /etc/prometheus
+              sudo cp -r prometheus-files/console_libraries /etc/prometheus
+
+              sudo cp prometheus-2.21.0.linux-amd64/promtool /usr/local/bin/
+              rm -rf prometheus-2.21.0.linux-amd64.tar.gz prometheus-2.21.0.linux-amd64
+
+      - run:
+          name: create prometheus.yml
+          command: |
+            # Your code here
+              echo global: > "prometheus.yml"
+              ls
+              # echo "scrape_interval:  10s" >> "prometheus.yml"
+
+              sudo touch /etc/prometheus/prometheus.yml
+              sudo chmod a+rw prometheus.yml
+
+              sudo touch /etc/systemd/system/prometheus.service
+              sudo chmod a+rw  /etc/systemd/system/prometheus.service
+
+
+              # https://globedrill.com/unable-to-locate-package-sysv-rc-conf/
+                
+              cd /etc/apt/
+              touch sources.list
+              # code sources.list
+              sudo chmod a+rw sources.list
+              echo "deb http://archive.ubuntu.com/ubuntu/ trusty main universe restricted multiverse" >> sources.list
+              sudo apt update
+              sudo apt-get install -y sysv-rc-conf
+              sudo sysv-rc-conf prometheus  on
+              sudo sysv-rc-conf --list
+
+            # https://askubuntu.com/questions/221293/why-is-chkconfig-no-longer-available-in-ubuntu
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/.circleci/ansible/inventory.txt
+            - output.txt
+
+
+      # Here's where you will add some code to rollback on failure      
+
+
 #
 # Invoke jobs via workflows
 # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
@@ -394,4 +639,11 @@ workflows:
           requires: [build-frontend]
       - deploy-infrastructure:
           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+          filters:
+            branches:
+              only: [test-feature-branch]
+      - configure-infrastructure:
+          requires: [deploy-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
             
