Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -204,52 +204,52 @@ jobs:
               pip install awscli
 
               # exit 1
-        # - run:
-        #     name: Configure server
-        #     command: |
-        #       # Your code here
-        #       pwd
-        #       cat .circleci/ansible/inventory.txt
+        - run:
+            name: Configure server
+            command: |
+              # Your code here
+              pwd
+              cat .circleci/ansible/inventory.txt
 
-        #       echo ENVIRONMENT=production > "backend/.env"
-        #       ls
-        #       # echo TYPEORM_CONNECTION=postgres >> "backend/.env"
-        #       # echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> "backend/.env"
-        #       # echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> "backend/.env"
-        #       # echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> "backend/.env"
-        #       echo NODE_ENV=production >> "backend/.env"
+              echo ENVIRONMENT=production > "backend/.env"
+              ls
+              # echo TYPEORM_CONNECTION=postgres >> "backend/.env"
+              # echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> "backend/.env"
+              # echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> "backend/.env"
+              # echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> "backend/.env"
+              echo NODE_ENV=production >> "backend/.env"
 
-        #       # echo TYPEORM_HOST=$TYPEORM_HOST >> "backend/.env"
-        #       # echo TYPEORM_PORT=$TYPEORM_PORT >> "backend/.env"
-        #       # echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
-        #       # echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
-        #       # echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"
-        #       ansible-playbook -i .circleci/ansible/inventory.txt .circleci/ansible/configure-server.yml
-        #       cat backend/.env
-        #       ls backend
+              # echo TYPEORM_HOST=$TYPEORM_HOST >> "backend/.env"
+              # echo TYPEORM_PORT=$TYPEORM_PORT >> "backend/.env"
+              # echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
+              # echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
+              # echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"
+              ansible-playbook -i .circleci/ansible/inventory.txt .circleci/ansible/configure-server.yml
+              cat backend/.env
+              ls backend
 
-        #       # exit 1
+              # exit 1
 
 
-        # Here's where you will add some code to rollback on failure  
-        # - run:
-        #     name: Install AWS CLI for rollback
-        #     when: on_fail
-        #     command: |
-        #       apk add --update py3-pip && pip3 install --upgrade pip && pip3 install awscli
-        # - persist_to_workspace:
-        #     root: ~/
-        #     paths:
-        #       - project/backend
-        # - destroy-environment:
-        #     workflow_id: "${CIRCLE_WORKFLOW_ID}"      
+      #  Here's where you will add some code to rollback on failure  
+        - run:
+            name: Install AWS CLI for rollback
+            when: on_fail
+            command: |
+              apk add --update py3-pip && pip3 install --upgrade pip && pip3 install awscli
+        - persist_to_workspace:
+            root: ~/
+            paths:
+              - project/backend
+        - destroy-environment:
+            workflow_id: "${CIRCLE_WORKFLOW_ID}"      
 
-        # - restore_cache:
-        #     keys: [backend-build]
-        # - run: 
-        #     name: Install dependencies
-        #     command: |
-        #       apk add --update ansible # install the dependencies needed
+        - restore_cache:
+            keys: [backend-build]
+        - run: 
+            name: Install dependencies
+            command: |
+              apk add --update ansible # install the dependencies needed
 
   # deploy-infrastructure:
   #   docker:
@@ -315,7 +315,7 @@ jobs:
 
 
 workflows:
-  autodeploy:
+  server-configuration:
     jobs:
       - build-frontend
       - build-backend
