Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -20,8 +20,7 @@ jobs:
     # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
     # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
     docker:
-      - image: circleci/node:13.8.0
-     # - image: cimg/node:13.8.0
+      - image: cimg/node:13.8.0
     # Add steps to the job
     # See: https://circleci.com/docs/2.0/configuration-reference/#steps
     steps:
@@ -129,51 +128,7 @@ jobs:
              npm audit --audit-level=critical
 
 
-  deploy-infrastructure:
-    docker:
-      - image: amazon/aws-cli
-    steps:
-      - checkout
-      - run: 
-          name: Install tar and gzip
-          command: |
-              yum -y install tar 
-              yum -y install gzip
-
-      - run:
-          name: Ensure back-end infrastructure exists
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/backend.yml \
-              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
-              --tags project=udapeople 
-              
-              
-      - run:
-          name: Ensure front-end infrastructure exists
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/frontend.yml \
-              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
-              --tags project=udapeople
-                   
-          
-      - run:
-          name: Add back-end ip to ansible inventory
-          command: |
-              echo [all] > .circleci/ansible/inventory.txt
-              aws ec2 describe-instances \
-                --query 'Reservations[*].Instances[*].PublicIpAddress' \
-                --output text >> inventory
-            
-      - persist_to_workspace:
-          root: ~/
-          paths:
-            - project/.circleci/ansible/inventory.txt
-            - output.txt
-         
+        
   configure-infrastructure:
       docker:
         # Docker image here that supports Ansible
@@ -182,7 +137,7 @@ jobs:
       steps: 
         # Checkout code from git
         # Add ssh keys with fingerprint
-        # attach workspace
+        # attach workspacefur
         # Install dependencies
         # Configure server
         - checkout
@@ -230,7 +185,7 @@ jobs:
               # exit 1
 
 
-      #  Here's where you will add some code to rollback on failure  
+        # Here's where you will add some code to rollback on failure  
         - run:
             name: Install AWS CLI for rollback
             when: on_fail
@@ -250,63 +205,69 @@ jobs:
             command: |
               apk add --update ansible # install the dependencies needed
 
-  # deploy-infrastructure:
-  #   docker:
-  #     # Docker image here that supports AWS CLI
-  #      - image: circleci/node:13.8.0
+  deploy-infrastructure:
+    docker:
+      # Docker image here that supports AWS CLI
+      # - image: circleci/node:13.8.0
+       - image: amazon/aws-cli
      
-  #   steps:
-  #     # Checkout code from git
-  #     - checkout
+    steps:
+      # Checkout code from git
+      - checkout
+      - run: 
+          name: Install tar and gzip
+          command: |
+              yum -y install tar 
+              yum -y install gzip
       
       
-  #     - run:
-  #         name: Ensure back-end infrastructure exists
-  #         command: |
-  #           aws cloudformation deploy \
-  #             # --template-file .circleci/files/backend.yml \
-  #             # --tags project=your-tag \
-  #             # --stack-name "your back-end stack name with workflow id" \
-  #             # --parameter-overrides ID="your workflow id"  
-  #             # exit 1
-  #             --template-file .circleci/files/backend.yml \
-  #             --tags project=udapeople \
-  #             --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} \
-  #             --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7} \
+      - run:
+          name: Ensure back-end infrastructure exists
+          command: |
+            aws cloudformation deploy \
+              # --template-file .circleci/files/backend.yml \
+              # --tags project=your-tag \
+              # --stack-name "your back-end stack name with workflow id" \
+              # --parameter-overrides ID="your workflow id"  
+              # exit 1
+              --template-file .circleci/files/backend.yml \
+              --tags project=udapeople \
+              --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} \
+              --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7} \
 
-  #     - run:
-  #         name: Ensure frontend infrastructure exists
-  #         command: |
-  #           aws cloudformation deploy \
-  #             # --template-file .circleci/files/frontend.yml \
-  #             # --tags project=your-tag \
-  #             # --stack-name "your front-end stack name with workflow id" \
-  #             # --parameter-overrides ID="your workflow id"  
-  #             # exit 1
+      - run:
+          name: Ensure frontend infrastructure exists
+          command: |
+            aws cloudformation deploy \
+              # --template-file .circleci/files/frontend.yml \
+              # --tags project=your-tag \
+              # --stack-name "your front-end stack name with workflow id" \
+              # --parameter-overrides ID="your workflow id"  
+              # exit 1
 
-  #             --template-file .circleci/files/frontend.yml \
-  #             --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7} \
-  #             --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7} \
-  #             --tags project=udapeople
+              --template-file .circleci/files/frontend.yml \
+              --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7} \
+              --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7} \
+              --tags project=udapeople
                    
-  #     - run:
-  #         name: Add backend IP to ansible inventory
-  #         command: |
-  #           # Your code here
-  #             echo [all] > .circleci/ansible/inventory.txt
-  #             aws ec2 describe-instances \
-  #               --query 'Reservations[*].Instances[*].PublicIpAddress' \
-  #               --output text >> inventory            
-  #           # exit 1
+      - run:
+          name: Add backend IP to ansible inventory
+          command: |
+            # Your code here
+              echo [all] > .circleci/ansible/inventory.txt
+              aws ec2 describe-instances \
+                --query 'Reservations[*].Instances[*].PublicIpAddress' \
+                --output text >> inventory            
+            # exit 1
 
-  #     - persist_to_workspace:
-  #         root: ~/
-  #         paths:
-  #           - project/.circleci/ansible/inventory.txt
-  #           - output.txt
-  #     # Here's where you will add some code to rollback on failure      
-  #     - destroy-environment:
-  #         workflow_id: "${CIRCLE_WORKFLOW_ID}" 
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/.circleci/ansible/inventory.txt
+            - output.txt
+      # Here's where you will add some code to rollback on failure      
+      - destroy-environment:
+          workflow_id: "${CIRCLE_WORKFLOW_ID}" 
 
 #
 # Invoke jobs via workflows
@@ -314,7 +275,7 @@ jobs:
 
 
 workflows:
-  server-configuration:
+  serverconfig:
     jobs:
       - build-frontend
       - build-backend
@@ -327,8 +288,6 @@ workflows:
           requires: [build-backend]
       - scan-frontend:
           requires: [build-frontend]
-      # - deploy-infrastructure:
-      #     requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-      #     filters:
-      #       branches:
-      #         only: [master]          
+      - deploy-infrastructure:
+          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+            
