configure infrastructure and deploy infrastructure added to jobs

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -127,6 +127,77 @@ jobs:
              npm audit fix --audit-level=critical --force
              npm audit --audit-level=critical
 
+              
+  configure-infrastructure:
+      docker:
+        # Docker image here that supports Ansible
+        - image: circleci/node:13.8.0
+        
+        
+        steps:
+        # Checkout code from git
+        # Add ssh keys with fingerprint
+        # attach workspace
+        # Install dependencies
+        # Configure server
+        - checkout
+        - add_ssh_keys:
+            fingerprints: ["19:a9:98:05:4a:cd:5c:1d:88:17:a8:30:dc:05:c5:4d"]
+
+        - attach_workspace:
+            at: ~/
+            
+        - run:
+            name: Install dependencies
+            command: |
+              # Your code here
+              apk add --update ansible
+              # exit 1
+        - run:
+            name: Configure server
+            command: |
+              # Your code here
+              pwd
+              cat .circleci/ansible/inventory.txt
+
+              echo ENVIRONMENT=production > "backend/.env"
+              ls
+              echo TYPEORM_CONNECTION=postgres >> "backend/.env"
+              echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> "backend/.env"
+              echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> "backend/.env"
+              echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> "backend/.env"
+              echo NODE_ENV=production >> "backend/.env"
+
+              echo TYPEORM_HOST=$TYPEORM_HOST >> "backend/.env"
+              echo TYPEORM_PORT=$TYPEORM_PORT >> "backend/.env"
+              echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
+              echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
+              echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"
+              ansible-playbook -i .circleci/ansible/inventory.txt .circleci/ansible/configure-server.yml
+              cat backend/.env
+              ls backend
+
+              # exit 1
+        # Here's where you will add some code to rollback on failure  
+        - run:
+            name: Install AWS CLI for rollback
+            when: on_fail
+            command: |
+              apk add --update py3-pip && pip3 install --upgrade pip && pip3 install awscli
+        - persist_to_workspace:
+            root: ~/
+            paths:
+              - project/backend
+        - destroy-environment:
+            workflow_id: "${CIRCLE_WORKFLOW_ID}"      
+
+        - restore_cache:
+            keys: [backend-build]
+        - run: 
+            name: Install dependencies
+            command: |
+              apk add --update ansible # install the dependencies needed
+
   deploy-infrastructure:
     docker:
       # Docker image here that supports AWS CLI
@@ -148,11 +219,11 @@ jobs:
               # exit 1
               --template-file .circleci/files/backend.yml \
               --tags project=udapeople \
-              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
+              --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} \
+              --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7} \
 
       - run:
-          name: Ensure front-end infrastructure exist
+          name: Ensure frontend infrastructure exists
           command: |
             aws cloudformation deploy \
               # --template-file .circleci/files/frontend.yml \
@@ -162,21 +233,28 @@ jobs:
               # exit 1
 
               --template-file .circleci/files/frontend.yml \
-              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
+              --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7} \
+              --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7} \
               --tags project=udapeople
                    
       - run:
-          name: Add back-end ip to ansible inventory
+          name: Add backend IP to ansible inventory
           command: |
             # Your code here
-            exit 1
+              echo [all] > .circleci/ansible/inventory.txt
+              aws ec2 describe-instances \
+                --query 'Reservations[*].Instances[*].PublicIpAddress' \
+                --output text >> inventory            
+            # exit 1
+
       - persist_to_workspace:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
+            - output.txt
       # Here's where you will add some code to rollback on failure      
-
+      - destroy-environment:
+          workflow_id: "${CIRCLE_WORKFLOW_ID}" 
 
 #
 # Invoke jobs via workflows
